### ISSUE TITLE
Bug parsing urls with IP address

### ISSUE THREAD

**Issue by Gamadril** [mihaigalos/url-parse#42]
`ftp://192.168.178.242/dir`- host part is parsed as `192.168.178.2`instead of `192.168.178.242`

```
fn main() {
    let url = url_parse::core::Parser::new(None)
    .parse("ftp://192.168.178.242/dir").unwrap();

    println!("{}", url.host_str().unwrap());
}
```

```
192.168.178.2
```

**Comment by mihaigalos** [comment]
Hi @Gamadril. I can confirm the bug. I'll be pushing out a fix.

**Comment by Gamadril** [comment]
thanks for the quick response and super fast fix. :+1:
